alter table "APPLICATIONS" add "SCHEMA_NAME" varchar2(400);
alter table "APPLICATIONS" add "APPS_DESCRIPTION" varchar2(4000);
alter table "APPLICATIONS" add "APPS_NAME" varchar2(4000);
alter table "APPLICATIONS" add "APPS_CODE" varchar2(800);
alter table "APPLICATIONS" add "DEFAULT_TABLE_PREFIX" varchar2(40);
alter table "APPS_PRIVS" add "APPS_CODE" varchar2(800);
alter table "APPS_PRIVS" add "FORM_CODE" varchar2(1020);
alter table "APPS_ROLE_MENUS" add "APP_MENU_ID" number(22, 0);
alter table "APPS_ROLE_MENUS" add "MENU_CODE" varchar2(4000);
alter table "APPS_ROLE_MENUS" add "PARENT_MENU_CODE" varchar2(4000);
alter table "APPS_ROLE_MENUS" add "POSITION" number(22, 9);
alter table "APPS_ROLE_MENUS" add "FORM_CODE" varchar2(4000);
alter table "APPS_ROLE_MENUS" add "ENABLED_FLAG" varchar2(4000);
alter table "APPS_ROLE_MENUS" add "DISPLAY_NAME" varchar2(4000);
alter table "APPS_ROLES" add "APPS_ROLE_ID" number(22, 0);
alter table "APPS_ROLES" add "ROLE_CODE" varchar2(4000);
alter table "APPS_ROLES" add "ROLE_NAME" varchar2(4000);
alter table "APPS_ROLES" add "APPS_CODE" varchar2(4000);
alter table "APPS_ROLES" add "ROOT_MENU_CODE" varchar2(4000);
alter table "APPS_ROLE_USERS" add "APP_ROLE_USER_ID" number(22, 0);
alter table "APPS_ROLE_USERS" add "ROLE_CODE" varchar2(4000);
alter table "APPS_ROLE_USERS" add "APPS_CODE" varchar2(4000);
alter table "APPS_ROLE_USERS" add "USER_ID" number(22, 0);
alter table "BINDS_V" add "FORM_CODE" varchar2(1020);
alter table "BINDS_V" add "POSITION" number(22, 0);
alter table "BINDS_V" add "DATATYPE" varchar2(1020);
alter table "BINDS_V" add "MAX_LENGTH" number(22, 0);
alter table "BINDS_V" add "ARRAY_LEN" number(22, 0);
alter table "BINDS_V" add "BIND_NAME" varchar2(1020);
alter table "FORM_ACTIONS" add "FORM_CODE" varchar2(1020);
alter table "FORM_ACTIONS" add "ACTION_CODE" varchar2(1020);
alter table "FORM_ACTIONS" add "PROCEDURE_NAME" varchar2(1020);
alter table "FORM_ACTIONS" add "ACTION_DISPLAY_NAME" varchar2(1020);
alter table "FORM_ACTIONS" add "ICON_ID" number(22, 0);
alter table "FORM_ACTIONS" add "DEFAULT_PARAM_PREFIX" varchar2(1020);
alter table "FORM_ACTIONS" add "DEFAULT_OLD_PARAM_PREFIX" varchar2(1020);
alter table "FORM_ACTIONS" add "ACTION_TYPE" varchar2(8);
alter table "FORM_ACTIONS" add "DISPLAY_NUMBER" number(22, 0);
alter table "FORM_ACTIONS" add "CONFIRM_TEXT" varchar2(4000);
alter table "FORM_ACTIONS" add "HOT_KEY" varchar2(1020);
alter table "FORM_ACTIONS" add "SHOW_SEPARATOR_BELOW" varchar2(4);
alter table "FORM_ACTIONS" add "DISPLAY_ON_TOOLBAR" varchar2(4);
alter table "FORM_ACTIONS" add "CHILD_FORM_CODE" varchar2(1020);
alter table "FORM_ACTIONS" add "URL_TEXT" varchar2(4000);
alter table "FORM_COLUMN_ACTIONS" add "FORM_COLUMN_ACTION_ID" number(22, 0);
alter table "FORM_COLUMN_ACTIONS" add "FORM_CODE" varchar2(1020);
alter table "FORM_COLUMN_ACTIONS" add "COLUMN_CODE" varchar2(1020);
alter table "FORM_COLUMN_ACTIONS" add "ACTION_CODE" varchar2(1020);
alter table "FORM_COLUMN_ACTIONS" add "ACTION_KEY_CODE" varchar2(1020);
alter table "FORM_COLUMN_ACTIONS" add "COL_ACTION_TYPE_CODE" varchar2(1020);
alter table "FORM_COLUMN_ATTR_VALS" add "FORM_COLUMN_ATTR_VAL_ID" number(22, 0);
alter table "FORM_COLUMN_ATTR_VALS" add "FORM_CODE" varchar2(1020);
alter table "FORM_COLUMN_ATTR_VALS" add "COLUMN_CODE" varchar2(1020);
alter table "FORM_COLUMN_ATTR_VALS" add "ATTRIBUTE_CODE" varchar2(1020);
alter table "FORM_COLUMN_ATTR_VALS" add "ATTRIBUTE_VALUE" varchar2(1020);
alter table "FORM_COLUMNS" add "FORM_CODE" varchar2(1020);
alter table "FORM_COLUMNS" add "COLUMN_CODE" varchar2(1020);
alter table "FORM_COLUMNS" add "COLUMN_USER_NAME" varchar2(1020);
alter table "FORM_COLUMNS" add "COLUMN_DISPLAY_SIZE" varchar2(1020);
alter table "FORM_COLUMNS" add "COLUMN_DATA_TYPE" varchar2(1020);
alter table "FORM_COLUMNS" add "COLUMN_DISPLAY_NUMBER" number(22, 0);
alter table "FORM_COLUMNS" add "PIMARY_KEY_FLAG" varchar2(4);
alter table "FORM_COLUMNS" add "SHOW_ON_GRID" varchar2(4);
alter table "FORM_COLUMNS" add "TREE_INITIALIZATION_VALUE" varchar2(4000);
alter table "FORM_COLUMNS" add "TREE_FIELD_TYPE" varchar2(8);
alter table "FORM_COLUMNS" add "EDITOR_TAB_CODE" varchar2(1020);
alter table "FORM_COLUMNS" add "FIELD_TYPE" varchar2(8);
alter table "FORM_COLUMNS" add "COLUMN_DESCRIPTION" varchar2(4000);
alter table "FORM_COLUMNS" add "IS_FROZEN_FLAG" varchar2(4);
alter table "FORM_COLUMNS" add "SHOW_HOVER_FLAG" varchar2(4);
alter table "FORM_COLUMNS" add "LOOKUP_CODE" varchar2(1020);
alter table "FORM_COLUMNS" add "HOVER_COLUMN_CODE" varchar2(1020);
alter table "FORM_COLUMNS" add "EDITOR_HEIGHT" varchar2(1020);
alter table "FORM_COLUMNS" add "LOOKUP_FIELD_TYPE" varchar2(4);
alter table "FORM_COLUMNS" add "HELP_TEXT" clob;
alter table "FORM_COLUMNS" add "TEXT_MASK" varchar2(1020);
alter table "FORM_COLUMNS" add "VALIDATION_REGEXP" varchar2(1020);
alter table "FORM_COLUMNS" add "DEFAULT_ORDERBY_NUMBER" varchar2(40);
alter table "FORM_COLUMNS" add "DEFAULT_VALUE" varchar2(1020);
alter table "FORM_COLUMNS" add "EDITOR_TITLE_ORIENTATION" varchar2(4);
alter table "FORM_COLUMNS" add "EDITOR_END_ROW_FLAG" varchar2(4);
alter table "FORM_COLUMNS" add "EDITOR_COLS_SPAN" varchar2(40);
alter table "FORM_COLUMNS" add "LOOKUP_DISPLAY_VALUE" varchar2(1020);
alter table "FORM_COLUMNS" add "EDITOR_ON_ENTER_KEY_ACTION" varchar2(1020);
alter table "FORM_COLUMNS$" add "COL_NUM" number(22, 0);
alter table "FORM_COLUMNS$" add "COL_TYPE" varchar2(1020);
alter table "FORM_COLUMNS$" add "COL_MAX_LEN" number(22, 0);
alter table "FORM_COLUMNS$" add "COL_NAME" varchar2(4000);
alter table "FORM_COLUMNS$" add "COL_NAME_LEN" number(22, 0);
alter table "FORM_COLUMNS$" add "COL_PRECISION" number(22, 0);
alter table "FORM_COLUMNS$" add "COL_SCALE" number(22, 0);
alter table "FORM_COLUMNS$" add "FORM_CODE" varchar2(1020);
alter table "FORM_COLUMNS$" add "PIMARY_KEY_FLAG" varchar2(4);
alter table "FORM_COLUMNS$" add "DEFAULT_COLUMN_WIDTH" varchar2(120);
alter table "FORM_COLUMNS$" add "COLUMN_DESCRIPTION" varchar2(4000);
alter table "FORM_PROPS" add "PROPERTY_LEVEL" varchar2(4000);
alter table "FORM_PROPS" add "PROPERTY_CODE" varchar2(4000);
alter table "FORM_PROPS" add "PROPERTY_NAME" varchar2(4000);
alter table "FORM_PROPS" add "DESCRIPTION" varchar2(4000);
alter table "FORM_PROPS" add "HELP_TEXT" clob;
alter table "FORM_PROPS" add "PROP_DATATYPE" varchar2(4000);
alter table "FORM_PROPS" add "PROPERTY_ID" number(22, 0);
alter table "FORM_PROP_VALUES" add "PROP_VALUE_ID" number(22, 0);
alter table "FORM_PROP_VALUES" add "FORM_CODE" varchar2(4000);
alter table "FORM_PROP_VALUES" add "PROPERTY_LEVEL" varchar2(4000);
alter table "FORM_PROP_VALUES" add "PROPERTY_CODE" varchar2(4000);
alter table "FORM_PROP_VALUES" add "PROP_VAL_LEVEL" varchar2(4000);
alter table "FORM_PROP_VALUES" add "VALUE_CHAR" varchar2(4000);
alter table "FORM_PROP_VALUES" add "VALUE_NUMBER" number(22, 0);
alter table "FORM_PROP_VALUES" add "VALUE_DATE" date;
alter table "FORM_PROP_VALUES" add "VALUE_CLOB" clob;
alter table "FORMS" add "FORM_CODE" varchar2(1020);
alter table "FORMS" add "HOT_KEY" varchar2(400);
alter table "FORMS" add "SQL_TEXT" varchar2(4000);
alter table "FORMS" add "FORM_NAME" varchar2(1020);
alter table "FORMS" add "FORM_TYPE" varchar2(4);
alter table "FORMS" add "SHOW_TREE_ROOT_NODE" varchar2(4);
alter table "FORMS" add "ICON_ID" number(22, 0);
alter table "FORMS" add "FORM_WIDTH" varchar2(120);
alter table "FORMS" add "FORM_HEIGHT" varchar2(120);
alter table "FORMS" add "BOTTOM_TABS_ORIENTATION" varchar2(8);
alter table "FORMS" add "SIDE_TABS_ORIENTATION" varchar2(8);
alter table "FORMS" add "SHOW_BOTTOM_TOOLBAR" varchar2(4);
alter table "FORMS" add "OBJECT_VERSION_NUMBER" number(22, 0);
alter table "FORMS" add "DEFAULT_COLUMN_WIDTH" varchar2(120);
alter table "FORMS" add "DESCRIPTION" clob;
alter table "FORMS" add "DOUBLE_CLICK_ACTION_CODE" varchar2(1020);
alter table "FORMS" add "LOOKUP_WIDTH" number(22, 0);
alter table "FORMS" add "APPS_CODE" varchar2(1020);
alter table "FORMS" add "EXPORT_ORDER" number(22, 0);
alter table "FORMS_V" add "APPS_CODE" varchar2(1020);
alter table "FORMS_V" add "EXPORT_ORDER" number(22, 0);
alter table "FORMS_V" add "FORM_CODE" varchar2(1020);
alter table "FORMS_V" add "HOT_KEY" varchar2(400);
alter table "FORMS_V" add "SQL_TEXT" varchar2(4000);
alter table "FORMS_V" add "FORM_NAME" varchar2(1020);
alter table "FORMS_V" add "DESCRIPTION" clob;
alter table "FORMS_V" add "FORM_TYPE" varchar2(4);
alter table "FORMS_V" add "SHOW_TREE_ROOT_NODE" varchar2(4);
alter table "FORMS_V" add "ICON_ID" number(22, 0);
alter table "FORMS_V" add "FORM_WIDTH" varchar2(120);
alter table "FORMS_V" add "FORM_HEIGHT" varchar2(120);
alter table "FORMS_V" add "BOTTOM_TABS_ORIENTATION" varchar2(8);
alter table "FORMS_V" add "SIDE_TABS_ORIENTATION" varchar2(8);
alter table "FORMS_V" add "SHOW_BOTTOM_TOOLBAR" varchar2(4);
alter table "FORMS_V" add "OBJECT_VERSION_NUMBER" number(22, 0);
alter table "FORMS_V" add "DEFAULT_COLUMN_WIDTH" varchar2(120);
alter table "FORMS_V" add "DOUBLE_CLICK_ACTION_CODE" varchar2(1020);
alter table "FORMS_V" add "LOOKUP_WIDTH" number(22, 0);
alter table "FORM_TAB_PARENT_EXCLNS" add "FORM_CODE" varchar2(4000);
alter table "FORM_TAB_PARENT_EXCLNS" add "TAB_CODE" varchar2(4000);
alter table "FORM_TAB_PARENT_EXCLNS" add "PARENT_FORM_CODE" varchar2(4000);
alter table "FORM_TAB_PARENT_EXCLNS" add "INCLUDED_FLAG" varchar2(8);
alter table "FORM_TAB_PARENT_EXCLNS" add "EXCLN_ID" number(22, 0);
alter table "FORM_TABS" add "FORM_CODE" varchar2(1020);
alter table "FORM_TABS" add "TAB_CODE" varchar2(1020);
alter table "FORM_TABS" add "CHILD_FORM_CODE" varchar2(1020);
alter table "FORM_TABS" add "TAB_POSITION" varchar2(4);
alter table "FORM_TABS" add "TAB_NAME" varchar2(1020);
alter table "FORM_TABS" add "NUMBER_OF_COLUMNS" number(22, 0);
alter table "FORM_TABS" add "ICON_ID" number(22, 0);
alter table "FORM_TABS" add "TAB_TYPE" varchar2(8);
alter table "FORM_TABS" add "TAB_DISPLAY_NUMBER" number(22, 0);
alter table "FORM_TABS_V" add "FORM_CODE" varchar2(1020);
alter table "FORM_TABS_V" add "TAB_CODE" varchar2(1020);
alter table "FORM_TABS_V" add "CHILD_FORM_CODE" varchar2(1020);
alter table "FORM_TABS_V" add "TAB_POSITION" varchar2(4);
alter table "FORM_TABS_V" add "TAB_NAME" varchar2(1020);
alter table "FORM_TABS_V" add "NUMBER_OF_COLUMNS" number(22, 0);
alter table "FORM_TABS_V" add "ICON_ID" number(22, 0);
alter table "FORM_TABS_V" add "TAB_TYPE" varchar2(8);
alter table "FORM_TABS_V" add "TAB_DISPLAY_NUMBER" number(22, 0);
alter table "GLOBAL_PARAMS" add "PARAM_NAME" varchar2(1020);
alter table "GLOBAL_PARAMS" add "PARAM_VALUE" varchar2(2000);
alter table "ICONS" add "ICON_ID" number(22, 0);
alter table "ICONS" add "ICON_FILE_NAME" varchar2(4000);
alter table "ICONS" add "ICON_PATH" varchar2(1020);
alter table "LOOKUP_ATTRIBUTES" add "LOOKUP_CODE" varchar2(1020);
alter table "LOOKUP_ATTRIBUTES" add "ATTRIBUTE_CODE" varchar2(1020);
alter table "LOOKUP_ATTRIBUTES" add "ATTRIBUTE_NAME" varchar2(1020);
alter table "LOOKUP_ATTRIBUTES" add "ATTRIBUTE_TYPE" varchar2(4);
alter table "LOOKUP_ATTRIBUTE_VALUES" add "LOOKUP_CODE" varchar2(1020);
alter table "LOOKUP_ATTRIBUTE_VALUES" add "LOOKUP_VALUE_CODE" varchar2(1020);
alter table "LOOKUP_ATTRIBUTE_VALUES" add "ATTRIBUTE_CODE" varchar2(1020);
alter table "LOOKUP_ATTRIBUTE_VALUES" add "ATTRIBUTE_VALUE_NUMBER" number(22, 0);
alter table "LOOKUP_ATTRIBUTE_VALUES" add "ATTRIBUTE_VALUE_CHAR" varchar2(4000);
alter table "LOOKUP_ATTRIBUTE_VALUES" add "ATTRIBUTE_VALUE_DATE" date;
alter table "LOOKUPS" add "LOOKUP_CODE" varchar2(1020);
alter table "LOOKUPS" add "LOOKUP_NAME" varchar2(1020);
alter table "LOOKUP_VALUES" add "LOOKUP_CODE" varchar2(1020);
alter table "LOOKUP_VALUES" add "LOOKUP_VALUE_CODE" varchar2(1020);
alter table "LOOKUP_VALUES" add "LOOKUP_DISPLAY_VALUE" varchar2(1020);
alter table "LOOKUP_VALUES" add "LOOKUP_VALUE_ID" number(22, 0);
alter table "MENUS" add "MENU_CODE" varchar2(1020);
alter table "MENUS" add "MENU_NAME" varchar2(1020);
alter table "MENUS" add "PARENT_MENU_CODE" varchar2(1020);
alter table "MENUS" add "MENU_FORM_CODE" varchar2(1020);
alter table "MENUS" add "MENU_POSITION" number(22, 0);
alter table "MENUS" add "SHOW_IN_NAVIGATOR" varchar2(4);
alter table "REPORT_TEMPLATES" add "REPORT_ID" number(22, 0);
alter table "REPORT_TEMPLATES" add "USER_ID" number(22, 0);
alter table "REPORT_TEMPLATES" add "APP_CODE" varchar2(1020);
alter table "REPORT_TEMPLATES" add "REPORT_TYPE_CODE" varchar2(1020);
alter table "REPORT_TEMPLATES" add "CONTENT_TYPE" varchar2(1020);
alter table "REPORT_TEMPLATES" add "CONTENT" blob;
alter table "REPORT_TEMPLATES" add "FILENAME" varchar2(1020);
alter table "REPORT_TEMPLATES" add "CLOB_CONTENT" clob;
alter table "TMP1" add "LVL" number(22, 0);
alter table "TMP1" add "MENU_CODE" varchar2(1020);
alter table "TMP1" add "PARENT_MENU_CODE" varchar2(1020);
alter table "TMP1" add "MENU_POSITION" number(22, 0);
alter table "TMP1" add "SHOW_IN_NAVIGATOR" varchar2(4);
alter table "TMP1" add "MENU_NAME" varchar2(1020);
alter table "TMP1" add "FORM_CODE" varchar2(1020);
alter table "TMP1" add "FORM_NAME" varchar2(1020);
alter table "TMP1" add "ICON_ID" number(22, 0);
alter table "TMP1" add "HOT_KEY" varchar2(400);
alter table "TMP1" add "DESCRIPTION" clob;
alter table "TMP1" add "CHILD_COUNT" number(22, 0);
alter table "USERS" add "USER_ID" number(22, 0);
alter table "USERS" add "FIO" varchar2(4000);
alter table "USERS" add "USERNAME" varchar2(1020);
alter table "USERS" add "PASSWORD" varchar2(255);
alter table "USERS" add "ORIG_REF_ID" number(22, 10);
alter table "USERS" add "EMAIL" varchar2(4000);

Comment On Column "FORM_ACTIONS"."CHILD_FORM_CODE" is 'Вызов дочерней формы в новом табе/окне';
Comment On Column "FORM_ACTIONS"."URL_TEXT" is 'URL после выполнения действия';
Comment On Column "FORM_COLUMN_ACTIONS"."FORM_COLUMN_ACTION_ID" is 'Ключ. Для обновления из интерфейса';
Comment On Column "FORM_COLUMN_ACTIONS"."FORM_CODE" is 'Код формы';
Comment On Column "FORM_COLUMN_ACTIONS"."COLUMN_CODE" is 'Код колонки';
Comment On Column "FORM_COLUMN_ACTIONS"."ACTION_CODE" is 'Код действия';
Comment On Column "FORM_COLUMN_ACTIONS"."ACTION_KEY_CODE" is 'Клавиша (для типа "по нажатию клавиши").';
Comment On Column "FORM_COLUMN_ACTIONS"."COL_ACTION_TYPE_CODE" is 'Тип действия (лукап FORM_COLUMNS.ACTION_TYPE)';
Comment On Column "FORM_COLUMN_ATTR_VALS"."FORM_COLUMN_ATTR_VAL_ID" is 'Id';
Comment On Column "FORM_COLUMN_ATTR_VALS"."FORM_CODE" is 'Идентификатор форм';
Comment On Column "FORM_COLUMN_ATTR_VALS"."COLUMN_CODE" is 'Идентификатор поля (из запроса)';
Comment On Column "FORM_COLUMN_ATTR_VALS"."ATTRIBUTE_CODE" is 'Код атрибута';
Comment On Column "FORM_COLUMN_ATTR_VALS"."ATTRIBUTE_VALUE" is 'значение атрибута';
Comment On Column "FORM_COLUMNS"."FORM_CODE" is 'Идентификатор форм';
Comment On Column "FORM_COLUMNS"."COLUMN_CODE" is 'Идентификатор поля (из запроса)';
Comment On Column "FORM_COLUMNS"."COLUMN_USER_NAME" is 'Пользовательское имя поля';
Comment On Column "FORM_COLUMNS"."COLUMN_DISPLAY_SIZE" is 'Ширина поля в писькелях';
Comment On Column "FORM_COLUMNS"."COLUMN_DATA_TYPE" is 'Тип данных (FORM_COLUMNS.DATA_TYPE)';
Comment On Column "FORM_COLUMNS"."COLUMN_DISPLAY_NUMBER" is 'Порядковый номер отображения в таблице';
Comment On Column "FORM_COLUMNS"."PIMARY_KEY_FLAG" is 'Признак того, что поле является первичным ключем (Y). Пусто - не является.';
Comment On Column "FORM_COLUMNS"."SHOW_ON_GRID" is 'Показывать в гриде';
Comment On Column "FORM_COLUMNS"."TREE_INITIALIZATION_VALUE" is 'Если не пусто и тип формы - "дерево" - используется при первом вызове дерева для инициализации. Аналогично конструкции Start With древовидных запросов';
Comment On Column "FORM_COLUMNS"."TREE_FIELD_TYPE" is 'Тип поля для дерева (Id, ParentId, ChildCount...)';
Comment On Column "FORM_COLUMNS"."EDITOR_TAB_CODE" is 'Ссылка на закладку формы редактирования. Если не указано - показывается только в гриде';
Comment On Column "FORM_COLUMNS"."FIELD_TYPE" is 'Тип поля, общий для дерева и грида';
Comment On Column "FORM_COLUMNS"."COLUMN_DESCRIPTION" is 'Описание поля (подсказка для пользователя)';
Comment On Column "FORM_COLUMNS"."IS_FROZEN_FLAG" is 'Замораживать поле?';
Comment On Column "FORM_COLUMNS"."SHOW_HOVER_FLAG" is 'Показывать всплывающую подсказку-значение поля';
Comment On Column "FORM_COLUMNS"."LOOKUP_CODE" is 'Ссылка на лукап - формау или простой';
Comment On Column "FORM_COLUMNS"."HOVER_COLUMN_CODE" is 'Поле той же формы, которое содержит подсказку. Если SHOW_HOVER_FLAG = ''Y'' и HOVER_COLUMN_CODE - подсказка берется из текущего поля (COLUMN_CODE)';
Comment On Column "FORM_COLUMNS"."EDITOR_HEIGHT" is 'Высота поля в закладке редактирования';
Comment On Column "FORM_COLUMNS"."LOOKUP_FIELD_TYPE" is 'См. Lookup FORM_COLUMNS.LOOKUP_FIELD_TYPE';
Comment On Column "FORM_COLUMNS"."HELP_TEXT" is 'Описание поля в HTML';
Comment On Column "FORM_COLUMNS"."TEXT_MASK" is 'Текстовая маска для поля. См. описание в интерфейсе';
Comment On Column "FORM_COLUMNS"."VALIDATION_REGEXP" is 'Регулярное выражение для клиентской валидации';
Comment On Column "FORM_COLUMNS"."DEFAULT_ORDERBY_NUMBER" is 'Порядок сортировки при открытии формы. "-" после цифры - сортировка по убыванию';
Comment On Column "FORM_COLUMNS"."DEFAULT_VALUE" is 'Значение по умолчанию для новых записей';
Comment On Column "FORM_COLUMNS"."EDITOR_TITLE_ORIENTATION" is 'item.setTitleOrientation';
Comment On Column "FORM_COLUMNS"."EDITOR_END_ROW_FLAG" is 'item.setEndRow';
Comment On Column "FORM_COLUMNS"."EDITOR_COLS_SPAN" is 'Редактор - количество колонок, занимаемых полем (item.setColSpan)';
Comment On Column "FORM_COLUMNS"."LOOKUP_DISPLAY_VALUE" is 'Поле запроса, отображаемое пользователю - для длинных лукапов';
Comment On Column "FORM_COLUMNS"."EDITOR_ON_ENTER_KEY_ACTION" is 'Действие по нажатию Enter';
Comment On Column "FORM_PROPS"."PROPERTY_LEVEL" is 'FORM->TAB->COLUMN-ACTION';
Comment On Column "FORM_PROPS"."PROPERTY_CODE" is 'напр SQL_TEXT';
Comment On Column "FORM_PROPS"."PROPERTY_NAME" is 'напр "Текст запроса"';
Comment On Column "FORM_PROPS"."DESCRIPTION" is 'Описание, для подсказки';
Comment On Column "FORM_PROPS"."HELP_TEXT" is 'HTML текст для подсказки в интерфейсе';
Comment On Column "FORM_PROPS"."PROP_DATATYPE" is 'Тип данных N(umber) D(ate) S(tring) B(oolean) L(OB)';
Comment On Column "FORM_PROPS"."PROPERTY_ID" is 'ID';
Comment On Column "FORM_PROP_VALUES"."PROP_VAL_LEVEL" is 'SYSTEM->APP->PARENT_FORM->ROLE->USER (System - для замены таблички FORM_COLUMNS$). Подумать о наследовании';
Comment On Column "FORMS"."FORM_CODE" is 'Текстовый идентификатор формы';
Comment On Column "FORMS"."HOT_KEY" is 'Горячая клавиша  - строка вида [Ctrl+][Alt+][Shift+]Chr. Регистр не важен';
Comment On Column "FORMS"."SQL_TEXT" is 'Order by во внешнем запросе не используйте, иначе при сортировке лететь будет..';
Comment On Column "FORMS"."FORM_NAME" is 'Имя формы для пользователя';
Comment On Column "FORMS"."FORM_TYPE" is 'Тип формы. G-грид, T-дерево...';
Comment On Column "FORMS"."SHOW_TREE_ROOT_NODE" is 'Показывать ли корневой узел для дерева?';
Comment On Column "FORMS"."FORM_WIDTH" is 'ширина в пикселях или процентах. * - авто';
Comment On Column "FORMS"."FORM_HEIGHT" is 'высота в пикселях или процентах. * - авто';
Comment On Column "FORMS"."BOTTOM_TABS_ORIENTATION" is 'ориентация нижних табиков детализации. см. FORMS.TABS_ORIENTATION';
Comment On Column "FORMS"."SIDE_TABS_ORIENTATION" is 'ориентация боковых табиков детализации. см. FORMS.TABS_ORIENTATION';
Comment On Column "FORMS"."SHOW_BOTTOM_TOOLBAR" is 'Показывать нижний тулбар?';
Comment On Column "FORMS"."DEFAULT_COLUMN_WIDTH" is 'Ширина полей по умолчанию';
Comment On Column "FORMS"."DESCRIPTION" is 'Описание формы... для коментариев при генерации пакета и т.д';
Comment On Column "FORMS"."DOUBLE_CLICK_ACTION_CODE" is 'Действие по двойному щелчку на записи. По умолчанию - редактирование';
Comment On Column "FORMS"."LOOKUP_WIDTH" is 'Ширина лукапа (если форма выступает в роли лукапа)';
Comment On Column "FORMS"."APPS_CODE" is 'Код приложения. Пока только для упрощения генерации скриптов';
Comment On Column "FORMS"."EXPORT_ORDER" is 'Порядковый номер при генерации скриптов';
Comment On Column "FORM_TAB_PARENT_EXCLNS"."EXCLN_ID" is 'ID';
Comment On Column "FORM_TABS"."FORM_CODE" is 'Идентификатор форм';
Comment On Column "FORM_TABS"."TAB_CODE" is 'Идентификатор закладки';
Comment On Column "FORM_TABS"."TAB_POSITION" is 'Lookup FORMS.EDITOR_POSITION';
Comment On Column "FORM_TABS"."TAB_NAME" is 'Пользовательское имя закладки';
Comment On Column "FORM_TABS"."NUMBER_OF_COLUMNS" is 'см. com.smartgwt.client.widgets.form.DynamicForm   setNumCols';
Comment On Column "FORM_TABS"."TAB_DISPLAY_NUMBER" is 'Порядок сортировки';
Comment On Column "ICONS"."ICON_FILE_NAME" is 'файл иконки по пути default_icon_path';
Comment On Column "LOOKUPS"."LOOKUP_CODE" is 'Текстовый идентфикатор (ID)';
Comment On Column "LOOKUPS"."LOOKUP_NAME" is 'Пользовательское имя';
Comment On Column "MENUS"."MENU_CODE" is 'Код меню';
Comment On Column "MENUS"."MENU_NAME" is 'Пользовательское наименование меню';
Comment On Column "MENUS"."PARENT_MENU_CODE" is 'Ссылка на пункт меню-родитель';
Comment On Column "MENUS"."MENU_FORM_CODE" is 'Ссылка на форму (для конечных узлов)';
Comment On Column "MENUS"."MENU_POSITION" is 'Позиция пунктов на одном уровне. Если не указано - то сначала нумерованные, потом по наименованию';
Comment On Column "MENUS"."SHOW_IN_NAVIGATOR" is 'Показывать в навигаторе';
