DROP ROLE fc_admin
/

CREATE ROLE fc_admin
NOT IDENTIFIED
/
GRANT EXECUTE ON FC22.APPLICATIONS_PKG TO fc_admin
/
GRANT EXECUTE ON FC22.APPS_ROLE_MENUS_PKG TO fc_admin
/
GRANT SELECT ON FC22.FORM_ACTIONS TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_ACTIONS_PKG TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_AUTH_CUR_USER_UTLIS_PKG TO fc_admin
/
GRANT SELECT ON FC22.FORM_COLUMN_ACTIONS TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_COLUMN_ACTIONS_PKG TO fc_admin
/
GRANT SELECT ON FC22.FORM_COLUMN_ATTR_VALS TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_COLUMN_ATTR_VALS_PKG TO fc_admin
/
GRANT SELECT ON FC22.FORM_COLUMNS TO fc_admin
/
GRANT SELECT ON FC22.FORM_COLUMNS$ TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_COLUMNS_PKG TO fc_admin
/
GRANT INSERT ON FC22.FORMS TO fc_admin
/
GRANT UPDATE ON FC22.FORMS TO fc_admin
/
GRANT SELECT ON FC22.FORMS TO fc_admin
/
GRANT EXECUTE ON FC22.FORMS_PKG TO fc_admin
/
GRANT SELECT ON FC22.FORMS_V TO fc_admin
/
GRANT SELECT ON FC22.FORM_TAB_PARENT_EXCLNS TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_TAB_PARENT_EXCLNS_PKG TO fc_admin
/
GRANT SELECT ON FC22.FORM_TABS TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_TABS_PKG TO fc_admin
/
GRANT SELECT ON FC22.FORM_TABS_V TO fc_admin
/
GRANT EXECUTE ON FC22.FORM_UTILS TO fc_admin
/
GRANT SELECT ON FC22.GLOBAL_PARAMS TO fc_admin
/
GRANT SELECT ON FC22.ICONS TO fc_admin
/
GRANT SELECT ON FC22.LOOKUP_ATTRIBUTES TO fc_admin
/
GRANT SELECT ON FC22.LOOKUP_ATTRIBUTE_VALUES TO fc_admin
/
GRANT EXECUTE ON FC22.LOOKUP_ATTRIBUTE_VALUES_PKG TO fc_admin
/
GRANT INSERT ON FC22.LOOKUPS TO fc_admin
/
GRANT SELECT ON FC22.LOOKUPS TO fc_admin
/
GRANT UPDATE ON FC22.LOOKUPS TO fc_admin
/
GRANT DELETE ON FC22.LOOKUPS TO fc_admin
/
GRANT DELETE ON FC22.LOOKUP_VALUES TO fc_admin
/
GRANT SELECT ON FC22.LOOKUP_VALUES TO fc_admin
/
GRANT UPDATE ON FC22.LOOKUP_VALUES TO fc_admin
/
GRANT INSERT ON FC22.LOOKUP_VALUES TO fc_admin
/
GRANT EXECUTE ON FC22.LOOKUP_VALUES_PKG TO fc_admin
/
GRANT SELECT ON FC22.MENUS TO fc_admin
/
GRANT EXECUTE ON FC22.MENUS_PKG TO fc_admin
/
GRANT SELECT ON FC22.REPORT_TEMPLATES TO fc_admin
/
GRANT EXECUTE ON FC22.TEXT_UTILS_PKG TO fc_admin
/
GRANT SELECT ON FC22.USERS TO fc_admin
/
GRANT EXECUTE ON FC22.USERS_PKG TO fc_admin
/

